spring:
  application:
    name: api_gateway

#  It allows the gateway to automatically route to services registered
#  with Eureka using their service names.
  cloud:
    gateway:
#      routes:
#        - id: foodService
#          uri: lb://FOODSERVICE
##         If our predicate is matched, then our request will be forwarded to the above URI.
#          predicates:
#            - Path=/food/**
#          filters:
#            - RewritePath=/food/?(?<remaining>.*), /$\{remaining}
#
#
#
#        - id: restaurantService
#          uri: lb://RESTAURANTSERVICE
##         If our predicate is matched, then our request will be forwarded to the above URI.
#          predicates:
#            - Path=/restaurant/**
#          filters:
#            - RewritePath=/restaurant/?(?<remaining>.*), /$\{remaining}

#     Inorder to create manual routes, the below should be false.
#     If you want gateway to create routes automatically, then enable it to true.
      discovery:
        locator:
          enabled: false

server:
  port: 9096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true


management:
#  It enables the /actuator/gateway/** endpoints (read-only mode),
#  which expose Spring Cloud Gateway internal info
  endpoint:
    gateway:
      access: read_only

# Enables all the actuator endpoints.
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Api Gateway"

